# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170922_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
