# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170922_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
